title: Ha Lab
description: Ha lab at the Fred Hutch
url: https://GavinHaLab.github.io
baseurl: "/"

markdown: kramdown
permalink: /:categories/:title/
future: true
repository: GavinHaLab


redcarpet:
  extensions:
   - tables
   - no_intra_emphasis
   - autolink
   - superscript
   - strikethrough

exclude:
  - "*.class"
  - "*.cpp"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.nb"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.branches"
  - "*.csv"
  - "*.fasta"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.newick"
  - "*.nex"
  - "*.tsv"
  - "*.tips"
  - "*.trees"
  - "*.txt"
  - "*.zip"
  - "*.gz"
  - "*.tiff"
  - "*.xml"
  - "Gemfile"
  - "Gemfile.lock"
 
projects:
  - GavinHaLab/TitanCNA_10X_snakemake
  - GavinHaLab/SV_10X_analysis
  - GavinHaLab/SV_WGS_analysis
  - GavinHaLab/mutect2_snakemake
  - gavinha/TitanCNA
  - GavinHaLab/ichorCNA
  - GavinHaLab/ichorCNA_offtarget
